GET http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjcwODEyNSwiZXhwIjoxNzQ3MzEyOTI1fQ.BkJywXGf5wN-f53-68xMSC-OYj5BvQQRfkBR0Hk1Awo

###
GET http://localhost:8080/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjcwODEyNSwiZXhwIjoxNzQ3MzEyOTI1fQ.BkJywXGf5wN-f53-68xMSC-OYj5BvQQRfkBR0Hk1Awo

###
POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "username": "test12",
  "email":"test12@test.com",
  "password":"test12"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"test12@test.com",
  "password":"test12"
}

###
POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "username": "employee12",
  "email":"employee12@employee.edu",
  "password":"employee12"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"employee12@employee.edu",
  "password":"employee12"
}

###

###
POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "username": "admin12",
  "email":"admin12@admin.edu",
  "password":"admin12"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email":"admin12@admin.edu",
  "password":"admin12"
}

###
GET http://localhost:8080/api/users/1/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjUxMDE0MSwiZXhwIjoxNzQ3MTE0OTQxfQ.cLS-ow77pKk7LafY9xtrtjgsBdlV9RM4cnWWEPfFEvM


###
GET http://localhost:8080/api/books/


###
POST http://localhost:8080/api/books/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjcwODEyNSwiZXhwIjoxNzQ3MzEyOTI1fQ.BkJywXGf5wN-f53-68xMSC-OYj5BvQQRfkBR0Hk1Awo

{
  "title": "The Let Them Theory: A Life-Changing Tool That Millions of People Can't Stop Talking About",
  "author":"Mel Robbins",
  "price": 183,
  "inventory": 100
}

###
DELETE http://localhost:8080/api/books/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjQzMTgxNSwiZXhwIjoxNzQ3MDM2NjE1fQ.LZSDzTp1wLJCOwosBB7ya9RxVvwnT4HNVCVzkWt_7lw

###
PUT http://localhost:8080/api/books/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjY5NTM3MywiZXhwIjoxNzQ3MzAwMTczfQ.aXlJqQ2joKx-jil6-l670KUKXgmLQDNBCDw9NBKUWMI

{
  "title": "admin12 test3 update",
  "author":"admin12",
  "price": 183,
  "inventory": 100
}

###
GET http://localhost:8080/api/books/1

###
GET http://localhost:8080/api/books/search/?txt="post"

###
GET http://localhost:8080/api/reservations/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjUxMDE0MSwiZXhwIjoxNzQ3MTE0OTQxfQ.cLS-ow77pKk7LafY9xtrtjgsBdlV9RM4cnWWEPfFEvM

###
GET http://localhost:8080/api/reservations/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjUxMDE0MSwiZXhwIjoxNzQ3MTE0OTQxfQ.cLS-ow77pKk7LafY9xtrtjgsBdlV9RM4cnWWEPfFEvM

###
POST http://localhost:8080/api/reservations/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjUxMDE0MSwiZXhwIjoxNzQ3MTE0OTQxfQ.cLS-ow77pKk7LafY9xtrtjgsBdlV9RM4cnWWEPfFEvM

{
  "title": "admin12 first reservations",
  "books": [
    {
      "id": 1,
      "title": "admin12 test...",
      "author": "admin12 content",
      "number": "1a710280-c4c0-40d4-857c-a529a19b95d9",
      "price": 103,
      "create_date": "2025-05-06",
      "update_date": null,
      "user_id": 1,
      "inventory": 100
    }
  ]
}

###
PUT http://localhost:8080/api/reservations/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MTJAdGVzdC5jb20iLCJpYXQiOjE3NDU5MDk1MTAsImV4cCI6MTc0NjUxNDMxMH0.6zbxdESI_WV5eS3iHMmJfZkOjza3x3DH0rJKMN5cnVw

{
  "title": "test12 title here..update",
  "author":"test12 content here....",
  "price": 171
}

###

DELETE  http://localhost:8080/api/reservations/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjEyQGFkbWluLmVkdSIsImlhdCI6MTc0NjUxMDE0MSwiZXhwIjoxNzQ3MTE0OTQxfQ.cLS-ow77pKk7LafY9xtrtjgsBdlV9RM4cnWWEPfFEvM
